### ISSUE TITLE
Models: Loo

### ISSUE THREAD

**Issue by mklemme** [mklemme/freepee#23]

**Comment by mklemme** [comment]
Has:
- Name*
- Address*
- Hours
- cost select: fee/customer only/no fee*
- baby changing type: boolean*
- Key required type: boolean*
- loo type: stalls / sinlge occupancy
- Shower type:boolean
- Tolietries provided type: boolean
- Hours through: yelp
- venue: Business/public*
- has_many ratings/comments

---

*required

**Comment by kourosh** [comment]
## Class Association

As discussed, I think we should use TDD and the "Outside In" development model. Having said that, I'm adding the association code here, for when we're ready.

`Class Loo < ActiveRecord::Base
  has_many :ratings
  has_many :users, through: :ratings
end`
